### ISSUE TITLE
It doesn't work now. 

### ISSUE THREAD

**Issue by Saurabh3012** [kirankaranth1/facebook-comment-spammer#4]
The script will successfully run but nothing gets posted on facebook page :-1:

**Comment by kirankaranth1** [comment]
Hey, I haven't been able to reproduce this. Maybe you're missing some permissions on the token? Or maybe it's something about the page? PFA screenshots (one of them is the code on my console, and the other is confirmation of the posted comment on the page). Note that I got a strange exception on my first hit by it's not something persistent and not a code issue nevertheless.
![scr1github](https://cloud.githubusercontent.com/assets/7852365/17454847/2061622e-5bc3-11e6-985e-f2cb6a1904f5.PNG)
![scr2](https://cloud.githubusercontent.com/assets/7852365/17454846/206098d0-5bc3-11e6-9d19-d1ee3bd52453.PNG)

**Comment by kirankaranth1** [comment]
Just tried this on Jabong and it worked. Closing this for now.

**Comment by kirankaranth1** [comment]
My suggestion to everyone facing this issue is to try the same set of commands on a Python console. The script suppresses errors returned from the facebook.publish() call.
