### ISSUE TITLE
raw_input

### ISSUE THREAD

**Issue by Satvik2101** [kirankaranth1/facebook-comment-spammer#7]
raw_input has been removed from Python. It should be replaced in the program and `(int)` added to the outside of the `input` code to convert the input into an integer

`int(input("bla bla bla"))`

**Comment by kauziishere** [comment]
Can you specify the Python version! Considering it is 3 I can handle this with a little bit of refactoring.

**Comment by kirankaranth1** [comment]
This project as a whole won't work now as mentioned in README.

**Comment by kirankaranth1** [comment]
This project as a whole won't work now as mentioned in README.
